Region.create!(name:"Africa")
Region.create!(name:"Americas")
Region.create!(name:"Asia")
Region.create!(name:"Europe")
Region.create!(name:"Oceania")

Subregion.create!(name:"Central Africa", region: Region.first)
Subregion.create!(name:"Eastern Africa", region: Region.first)
Subregion.create!(name:"Northern Africa", region: Region.first)
Subregion.create!(name:"Southern Africa", region: Region.first)
Subregion.create!(name:"Western Africa", region: Region.first)

Country.create!(name:"Angola", subregion: Subregion.first)
Country.create!(name:"Cameroon", subregion: Subregion.first)
Country.create!(name:"Central African Republic", subregion: Subregion.first)
Country.create!(name:"Chad", subregion: Subregion.first)
Country.create!(name:"Democratic Republic of the Congo", subregion: Subregion.first)
Country.create!(name:"Republic of the Congo", subregion: Subregion.first)
Country.create!(name:"Equatorial Guinea", subregion: Subregion.first)
Country.create!(name:"Gabon", subregion: Subregion.first)
Country.create!(name:"São Tomé and Príncipe", subregion: Subregion.first)
